name: 'Publish integration image to DockerHub'
description: 'Builds and publishes graph integration project to DockerHub'
inputs:
  package-name:  # id of input
    description: 'Name of package to publish to DockerHub'
    required: true
  docker-username:  # id of input
    description: 'Docker username to auth and publish'
    required: true
  docker-password:  # id of input
    description: 'Docker username to auth and publish'
    required: true
runs:
  using: "composite"
  steps:
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Docker meta
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ package-name }}
        # generate Docker tags based on the following events/attributes
        tags: |
           type=schedule
           type=ref,event=branch
           type=ref,event=pr
           type=semver,pattern={{version}}
           type=semver,pattern={{major}}.{{minor}}
           type=semver,pattern={{major}}
           type=sha
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
